apiVersion: v1
kind: Pod
metadata:
     name:    auth-app-pod
     labels:  
        name: auth-app-pod       
        app:  deepak-movie-app
      

spec:
    containers:
    - name: auth-app
      image: auth-service
      ports: 
       - containerPort: 9100
    