apiVersion: v1
kind: Service
metadata:
     name:    auth-service
     lablels:  
        name: auth-service       
        app:  deepak-movie-app
      

spec:
      type: LoadBalancer  
      ports: 
      -port: 9100    
       targetPort: 9100
      selector:
        name: auth-app-pod       
        app:  deepak-movie-app
    