apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  selector:
    matchLabels:
      app: auth-app
      tier: backend
      track: stable
  replicas: 0
  template:
    metadata:
      labels:
        app: auth-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: auth-pod
          image: fabmittal/auth-service
          ports:
            - name: http
              containerPort: 9100
