apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app
spec:
  selector:
    matchLabels:
      app: booking-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: booking-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: booking-pod
          image: fabmittal/booking-service
          ports:
            - name: http
              containerPort: 8200
