apiVersion: v1
kind: Service
metadata:
     name:    movie-service
     lablels:  
        name: movie-service       
        app:  deepak-movie-app
      

spec:
      type: LoadBalancer
      ports: 
      -port: 8100    
       targetPort: 8100
      selector:
        name: movie-app-pod       
        app:  deepak-movie-app            
    